site:
  name: Unsuspicious Industries
  acronym: USI
  site: 'https://unsuspicious.org'
  base: ''
  trailingSlash: false


# Default SEO metadata
metadata:
  title:
    default: USI
    template: '%s — USI'
  description: "\U0001F680 Unsuspicious Industries is a multidisciplinary tech company that specializes in creating innovative solutions for the modern world. We are a team of passionate individuals who are dedicated to creating the best products and services for our clients. Our goal is to make the world a better place by providing cutting-edge technology that is both reliable and efficient\U0001F680"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: USI
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@unsuspiciousind'
    site: '@unsuspiciousind'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"

  tokens:
    default:
      fonts:
        sans: Aurora
        serif: var(--ph-font-sans)
        heading: var(--ph-font-sans)
      colors:
        default: rgb(0, 0, 255) # blue text
        heading: rgb(0, 0, 255) # blue headings
        muted: rgb(0, 0, 255) # blue muted text
        bgPage: rgb(255, 255, 255) # white background
        primary: rgb(70, 130, 180) # clear blue primary color
        secondary: rgb(70, 130, 180) # clear blue secondary color
        accent: rgb(70, 130, 180) # clear blue accent color
        info: rgb(70, 130, 180) # clear blue info color
        success: rgb(70, 130, 180) # clear blue success color
        warning: rgb(70, 130, 180) # clear blue warning color
        error: rgb(70, 130, 180) # clear blue error color
        link: rgb(70, 130, 180) # clear blue link color
        linkActive: rgb(70, 130, 180) # clear blue active link color
    dark:
      fonts: {}
      colors:
        default: rgb(255, 255, 255) # white text in dark mode
        heading: rgb(255, 255, 255) # white headings in dark mode
        muted: rgb(255, 255, 255) # white muted text in dark mode
        bgPage: rgb(70, 130, 180) # clear blue background in dark mode
        primary: rgb(255, 255, 255) # white primary color in dark mode
        secondary: rgb(255, 255, 255) # white secondary color in dark mode
        accent: rgb(255, 255, 255) # white accent color in dark mode
        info: rgb(255, 255, 255) # white info color in dark mode
        success: rgb(255, 255, 255) # white success color in dark mode
        warning: rgb(255, 255, 255) # white warning color in dark mode
        error: rgb(255, 255, 255) # white error color in dark mode
        link: rgb(255, 255, 255) # white link color in dark mode
        linkActive: rgb(255, 255, 255) # white active link color in dark mode

ui:
  theme: "dark:only"

  tokens:
    default:
      fonts:
        sans: Ubuntu
        serif: var(--ph-font-sans)
        heading: var(--ph-font-sans)
      colors:
        default: rgb(0, 0, 255) # blue text
        heading: rgb(0, 0, 255) # blue headings
        muted: rgb(0, 0, 255) # blue muted text
        bgPage: rgb(255, 255, 255) # white background
        primary: rgb(70, 130, 180) # clear blue primary color
        secondary: rgb(70, 130, 180) # clear blue secondary color
        accent: rgb(70, 130, 180) # clear blue accent color
        info: rgb(70, 130, 180) # clear blue info color
        success: rgb(70, 130, 180) # clear blue success color
        warning: rgb(70, 130, 180) # clear blue warning color
        error: rgb(70, 130, 180) # clear blue error color
        link: rgb(70, 130, 180) # clear blue link color
        linkActive: rgb(70, 130, 180) # clear blue active link color
    dark:
      fonts: 
        sans: Ubuntu
        serif: var(--ph-font-sans)
        heading: var(--ph-font-sans)
      colors:
        default: rgb(255, 255, 255) # white text in dark mode
        heading: rgb(255, 255, 255) # white headings in dark mode
        muted: rgb(255, 255, 255) # white muted text in dark mode
        bgPage: rgb(70, 130, 180) # clear blue background in dark mode
        primary: rgb(255, 255, 255) # white primary color in dark mode
        secondary: rgb(255, 255, 255) # white secondary color in dark mode
        accent: rgb(255, 255, 255) # white accent color in dark mode
        info: rgb(255, 255, 255) # white info color in dark mode
        success: rgb(255, 255, 255) # white success color in dark mode
        warning: rgb(255, 255, 255) # white warning color in dark mode
        error: rgb(255, 255, 255) # white error color in dark mode
        link: rgb(255, 255, 255) # white link color in dark mode
        linkActive: rgb(255, 255, 255) # white active link color in dark mode